apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-crds
  #this finaliser causes cascading deletion (delete children)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: unterbau
  source:
    path: manifests/csi-crds
    repoURL: "https://github.com/AtomSoldat/private-cloud.git"
    targetRevision: master
